### ISSUE TITLE
HTTP Error 404 during compleasm download

### ISSUE THREAD

**Issue by brandonlind** [huangnengCSU/compleasm#50]
I'm attempting to download embryophyta_odb12 and viridiplantae_odb12. However I get an error for both: `urllib.error.HTTPError: HTTP Error 404: Not Found`. 

I get errors with these dbs but not with eudicotyledons_odb12.

I'm running compleasm 0.2.7. Installed with `conda create -n compleasm_0_2_7 -c conda-forge -c bioconda compleasm`

here is the full traceback for embryophyta_odb12
```python
Traceback (most recent call last):
  File "/path/to/anaconda3/envs/compleasm_0_2_7/bin/compleasm", line 10, in <module>
    sys.exit(main())
  File "/path/to/anaconda3/envs/compleasm_0_2_7/lib/python3.9/site-packages/compleasm.py", line 2229, in main
    args.func(args)
  File "/path/to/anaconda3/envs/compleasm_0_2_7/lib/python3.9/site-packages/compleasm.py", line 1988, in download
    downloader.download_lineage(lineage, args.odb)
  File "/path/to/anaconda3/envs/compleasm_0_2_7/lib/python3.9/site-packages/compleasm.py", line 165, in download_lineage
    download_success = self.download_single_file(remote_url, download_path, expected_hash)
  File "/path/to/anaconda3/envs/compleasm_0_2_7/lib/python3.9/site-packages/compleasm.py", line 90, in download_single_file
    urllib.request.urlretrieve(remote_filepath, local_filepath)
  File "/path/to/anaconda3/envs/compleasm_0_2_7/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/path/to/anaconda3/envs/compleasm_0_2_7/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/path/to/anaconda3/envs/compleasm_0_2_7/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/path/to/anaconda3/envs/compleasm_0_2_7/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/path/to/anaconda3/envs/compleasm_0_2_7/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/path/to/anaconda3/envs/compleasm_0_2_7/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/path/to/anaconda3/envs/compleasm_0_2_7/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by huangnengCSU** [comment]
Hi @brandonlind ,

Could you clone from souce code and run `compleasm.py` again. The structure of the BUSCO dataset has changed recently, and I have updated the code, but it has not yet been synced to the conda. Regarding the HTTP error, it is likely a network issue. I just tested downloading both lineages and it was successful.

**Comment by brandonlind** [comment]
Hi @huangnengCSU  I downloaded from source and still receive the same error message.

I can download eudicotyledons_odb12 without issue though, so not sure it's a network issue?

**Comment by brandonlind** [comment]
EDIT - maybe it is, I can download on my local machine. I will follow up with IT
